# Generated by Django 5.2.5 on 2025-09-15 11:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('stagiaire', 'Stagiaire'), ('entreprise', 'Entreprise'), ('administrateur', 'Administrateur')], default='stagiaire', max_length=20)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id_entreprise', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(default='', max_length=30)),
                ('domaine_expertise', models.CharField(default='', max_length=100)),
                ('localisation_entreprise', models.CharField(default='', max_length=30)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profil_entreprise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id_offre', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre_poste', models.CharField(default='', max_length=30)),
                ('domaine_poste', models.CharField(max_length=100)),
                ('description_offre', models.TextField(max_length=1000)),
                ('type_offre', models.CharField(max_length=50)),
                ('type_contrat', models.CharField(max_length=50)),
                ('localisation_offre', models.CharField(default='', max_length=100)),
                ('date_fin_candidature', models.DateField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='app_premier_stage.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id_stagiaire', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_stagiaire', models.CharField(default='', max_length=30)),
                ('prenom_stagiaire', models.CharField(default='', max_length=100)),
                ('date_naissance_stagiaire', models.DateField()),
                ('telephone_stagiaire', models.CharField(default='+225', max_length=15)),
                ('filiere_stagiaire', models.CharField(default='', max_length=30)),
                ('cv_stagiaire', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profil_stagiaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id_candidature', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut_candidature', models.CharField(default='envoyee', max_length=15)),
                ('date_postulation', models.DateTimeField(auto_now_add=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='app_premier_stage.offreemploi')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='app_premier_stage.stagiaire')),
            ],
        ),
    ]
