# Generated by Django 5.2.5 on 2025-09-01 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id_entreprise', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(default='', max_length=30)),
                ('domaine_expertise', models.CharField(default='', max_length=100)),
                ('localisation_entreprise', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id_offre', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre_poste', models.CharField(default='', max_length=30)),
                ('domaine_poste', models.CharField(max_length=100)),
                ('description_offre', models.CharField(max_length=300)),
                ('type_offre', models.CharField(max_length=50)),
                ('type_contrat', models.CharField()),
                ('localisation_offre', models.CharField(default='', max_length=100)),
                ('date_fin_candidature', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id_stagiaire', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_stagiaire', models.CharField(default='', max_length=30)),
                ('prenom_stagiaire', models.CharField(default='', max_length=100)),
                ('date_naissance_stagiaire', models.DateField()),
                ('email_stagiaire', models.EmailField(max_length=254)),
                ('telephone_entreprise', models.CharField(default='+225', max_length=15)),
                ('contact_stagiaire', models.CharField()),
                ('cv_stagiaire', models.Field()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
