# Generated by Django 5.2.5 on 2025-09-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premier_stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='description_offre',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='domaine_poste',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='type_contrat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='type_offre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
