# Generated by Django 5.2.5 on 2025-09-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premier_stage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='etablissement',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='stagiaire',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_stagiaire'),
        ),
    ]
