# Generated by Django 5.2.5 on 2025-09-16 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premier_stage', '0002_stagiaire_etablissement_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stagiaire',
            name='unique_user_stagiaire',
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='offres_entreprise', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut_candidature',
            field=models.CharField(default='envoyée', max_length=15),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_entreprise', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_stagiaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('stagiaire', 'offre'), name='unique_candidature'),
        ),
    ]
