# Generated by Django 5.2.5 on 2025-09-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premier_stage', '0002_alter_offreemploi_description_offre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreemploi',
            name='type_contrat',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='type_offre',
            field=models.CharField(default='', max_length=150),
        ),
    ]
