# Generated by Django 5.2.5 on 2025-09-16 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premier_stage', '0003_remove_stagiaire_unique_user_stagiaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_postule', to='app_premier_stage.offreemploi'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to='app_premier_stage.stagiaire'),
        ),
    ]
