# Generated by Django 5.2.5 on 2025-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premier_stage', '0003_alter_offreemploi_type_contrat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='description_entreprise',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut_candidature',
            field=models.CharField(default='candidature envoyée', max_length=15),
        ),
    ]
