# Generated by Django 5.2.5 on 2025-09-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premier_stage', '0004_entreprise_description_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_entretien',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='heure_entretien',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='description_entreprise',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nombre_employe',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='site_entreprise',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='competence_requis',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='description_offre',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='duree_contrat',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='mission_offre',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='remuneration_offre',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='type_contrat',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
