# Generated by Django 5.2.5 on 2025-09-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premier_stage', '0004_alter_candidature_offre_alter_candidature_stagiaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='email_stagiaire',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
