# Generated by Django 5.2.5 on 2025-09-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_premier_stage', '0005_stagiaire_email_stagiaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='email_entreprise',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='nombre_employe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='telephone_entreprrise',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='competence_requis',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='date_debut_offre',
            field=models.DateField(default='AAAA-MM-JJ'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='duree_contrat',
            field=models.DateField(default='AAAA-MM-JJ'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='mission_offre',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='remuneration_offre',
            field=models.CharField(default='', max_length=10),
        ),
    ]
