from . import views
from django.urls import path

urlpatterns = [
    path('',views.Index,name="Accueil"),
    path('Connexion/',views.Connexion,name='connexion'),
    path('Deconnexion',views.Deconnexion,name="deconnexion"),
    path('diplome/detailoffre/<uuid:pk>/',views.DetailOffre,name='detail'),
    path('offres/',views.Offres,name='offres'),
    path('postuler/<uuid:pk>/',views.Postuler,name='postuler'),
    path('entreprise/',views.EntrepriseDashboard,name='entreprise'),
    path('diplome/',views.DiplomeDashboard,name='diplome'),
    path('admindashboard/',views.AdminDashboard,name='admindashboard'),
    path('statistique/',views.Statistiques,name="statistique"),
    path('preinscription/',views.Preinscription,name="preinscription"),
    path('inscriptionDiplome/',views.RegisterDiplome,name="inscriptionDiplome"),
    path('completeprofil/',views.CompleteProfil,name="completeprofil"),
    path('inscriptionEntreprise/',views.RegisterEntreprise,name="inscriptionEntreprise"),
    path('administrateur/validerentreprise/<uuid:pk>/',views.ValiderEntreprise,name="validerentreprise"),
    path('detailCandidature/<uuid:pk>/',views.DetailCandidature,name="detailcandidature"),
    path('candidature/',views.Mescandidatures,name='candidature'),
    path('profilCandidat/',views.profilUpdate,name='profilcandidat'),
    path('entreprise/offreCree/',views.OffreCree,name='offrecree'),
    path('entreprise/listestagiaire/',views.EntrepriseListeStagiaire,name="entreprise_liste_stagiaire"),
    path('entreprise/mesoffres/',views.MesOffres,name="mesoffres"),
    path("entreprise/supprimeroffre/<uuid:pk>/",views.SupprimerOffre,name="supprimer_offre"),
    path("entreprise/modifieroffre/<uuid:pk>/",views.ModifierOffre,name="modifier_offre"),
    path("entreprise/profil/",views.ProfilEntreprise,name="profil_entreprise"),
    path('entreprise/candidature/<uuid:pk>/',views.Listecandidature,name="liste_candidatures"),
    path('entreprise/detailcandidat/<uuid:pk>/',views.Detailcandidat,name="detailcandidat"),
    path("administrateur/entreprise/",views.ListeEntreprise,name="liste_entreprise"),
    path("administrateur/listeoffre/",views.ListeOffre,name="liste_offres"),
    path("administrateur/stagiaire/",views.ListeStagiaire,name="liste_stagiaires"),
    path("administrateur/candidature",views.AdminCandidature,name="admin_candidatures"),
    path("administrateur/detailcandidature/<uuid:pk>/",views.AdminDetailCandidature,name="detailcandidature"),
    path("administrateur/detailentreprise/<uuid:pk>/",views.AdminDetailEntreprise,name="detailentreprise"),
    path("administrateur/detailstagiaire/<uuid:pk>/",views.AdminDetailStagiaire,name="detailstagiaire"),
]

